---
- name: Install mysql.
  hosts: "databases"
  become: true
  become_user: root
  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - {role: geerlingguy.mysql}
      
      
