---
- name: Install apache using own role.
  hosts: "webservers"
  become: true
  become_user: root
  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'

    - { role: geerlingguy.php-versions }
    - { role: geerlingguy.php }
    - { role: geerlingguy.composer }

